branches:
  only:
    - develop
sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - postfix
  chrome: stable
  hosts:
    - magento2.travis
services:
  - rabbitmq
  - elasticsearch
  - mysql
language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
env:
  global:
    - MAGENTO_HOST_NAME="magento2.travis"
    - MAGENTO_PROTOCOL="https"
    - MAGENTO_BACKEND="backend"
    - MAGENTO_ADMIN_USERNAME="admin"
    - MAGENTO_ADMIN_PASSWORD="123123q"
    - ADOBE_STOCK_LICENSED_IMAGE="175947395"
    - ADOBE_STOCK_UNLICENSED_IMAGE="24860368"
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=phpstan
    - TEST_SUITE=static
    # List out subsets of functional tests to run separately to fit under travis timeout (50mins)
    # TODO: this is hacky, is there a better way?
    - TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_filters
    - TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_grid
    - TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_preview
    - TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_configuration
    - TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_keywords
    - TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_ims
    - TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_see_more
    - TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_license
matrix:
  fast_finish: true
jobs:
  # only run MFTF tests on PHP 7.3
  exclude:
    - php: '7.1'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_filters
    - php: '7.1'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_grid
    - php: '7.1'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_preview
    - php: '7.1'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_configuration
    - php: '7.1'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_keywords
    - php: '7.1'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_ims
    - php: '7.1'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_see_more
    - php: '7.1'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_license
    - php: '7.2'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_filters
    - php: '7.2'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_grid
    - php: '7.2'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_preview
    - php: '7.2'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_configuration
    - php: '7.2'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_keywords
    - php: '7.2'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_ims
    - php: '7.2'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_see_more
    - php: '7.2'
      env: TEST_SUITE=functional MFTF_SUITE=adobe_stock_integration_suite_license
cache:
  directories:
    - $HOME/.composer/cache
    # cache location of webdrivers for MFTF (chromedriver, geckdriver, etc)
    - $HOME/drivers
before_install:
  - bash -x dev/travis/before_install.sh
install:
  - mkdir -p magento2/app/code/Magento
  - mv Adobe* magento2/app/code/Magento/.
  - pushd magento2
  - composer install
  - composer require astock/stock-api-libphp
  - popd
before_script:
  - bash -x dev/travis/before_script.sh
script:
  - bash -x dev/travis/script.sh
after_success:
  - if [ $TEST_SUITE == 'unit' ]; then travis_retry coveralls; fi
after_failure:
  - bash -x dev/travis/after_failure.sh
