sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - postfix
  firefox: latest
  hosts:
    - magento2.travis
services:
  - rabbitmq
  - elasticsearch
language: php
php:
  #- '7.1'
  #- '7.2'
  - '7.3'
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - NODE_JS_VERSION=8
    - MAGENTO_HOST_NAME="magento2.travis"
    - MAGENTO_PROTOCOL="http"
    - MAGENTO_ADMIN_USERNAME="admin"
    - MAGENTO_ADMIN_PASSWORD="123123q"
  matrix:
    #- TEST_SUITE=unit
    #- TEST_SUITE=phpstan
    - TEST_SUITE=functional
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm
    - $HOME/node_modules
    - $HOME/yarn.lock
before_install:
  - ./dev/travis/before_install.sh
install:
  - mkdir -p magento2/app/code/Magento
  - mv Adobe* magento2/app/code/Magento/.
  - pushd magento2
  - composer install
  - composer require astock/stock-api-libphp
  - popd
before_script:
  - pushd magento2
  - ./dev/travis/before_script.sh
  - popd
script:
  - pushd magento2
  - if [ $TEST_SUITE == 'unit' ]; then phpunit --configuration dev/tests/unit/phpunit.xml; fi
  - if [ $TEST_SUITE == 'phpstan' ]; then composer require --dev phpstan/phpstan fooman/phpstan-magento2-magic-methods && phpstan analyse -l 2 ../ext -a dev/tests/api-functional/framework/autoload.php ; fi
  - if [ $TEST_SUITE == 'functional' ]; then codecept run functional --verbose --steps -g AdobeStockIntegration -c dev/tests/acceptance/codeception.yml; fi
after_success:
  - if [ $TEST_SUITE == 'unit' ]; then cd ../ && travis_retry coveralls; fi
